#Git
alias gad='git add'
alias gch='git checkout'
alias gcl='git clone'
alias gco='git commit'
alias gdf='git diff'
alias gfu='git fetch upstream'
alias glo='git log'
alias gpl='git pull'
alias gpu='git push'
alias gre='git remote -v'
alias gst='git status'
alias gss='git stash save'
alias gsp='git stash pop'

alias og='origin'
