#!/bin/bash

set -e

DOTFILES=~/dotfiles
echo "Installing $DOTFILES"

# TODO: prompt for installing packages
# pip install -r $DOTFILES/requirements.txt
# curl https://sh.rustup.rs -sSf | bash -s -- -y
# cat $DOTFILES/cargo.list | xargs cargo install

if [ ! -d $DOTFILES ]; then
    echo "Cloning dotfiles repo"
    git clone git@github.com:apeduru/dotfiles.git $DOTFILES
fi

cd $DOTFILES
echo "Setting local git config for the dotfiles repo"
git config user.name "Ansley Peduru"
git config user.email "ansleypeduru96@gmail.com"

if [ "$(uname)" == "Darwin"  ]; then
  if  [ ! -e $(which brew) ]; then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi
  brew update
  brew bundle
else
  apt update
  cat $DOTFILES/packages.list | xargs sudo apt-get --yes install
fi

rcup -d $DOTFILES -v

exit 0
