#!/usr/bin/env bash

set -e

DOTFILES=~/dotfiles

err() {
  echo "$1"
  exit 1
}

get_dotfiles() {
  echo "Installing $DOTFILES"

  if [ ! -d $DOTFILES ]; then
    echo "Cloning dotfiles repo"

    url="https://"
    if [[ -n "${TOKEN}" ]]; then
      url=""$url""${TOKEN}"@"
    fi
    repo=""$url"github.com/apeduru/dotfiles.git"

    git clone "$repo" "$DOTFILES"
  else
    err "$DOTFILES already exists"
  fi

  cd $DOTFILES
}

which -s git || err "required tool missing: git"
which -s make || err "required tool missing: make"

case "$(uname -s)" in 
  Darwin)
    get_dotfiles
    which -s brew || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew update
    brew bundle

    make up
    ;;
  Linux)
    which -s apt || err "Unsupported Linux"
    get_dotfiles
    sudo apt update
    cat $DOTFILES/packages.list | xargs sudo apt-get --yes install

    make up
    ;;
  *)
    err "Unrecognized OS"
    ;;
esac

exit 0
