#!/usr/bin/env bash

set -e

DOTFILES=~/dotfiles

err() {
  echo "$1"
  exit 1
}

get_dotfiles() {
  echo "Installing $DOTFILES"

  if [ ! -d $DOTFILES ]; then
    echo "Cloning dotfiles repo"

    url="https://"
    if [[ -n "${TOKEN}" ]]; then
      url=""$url""${TOKEN}"@"
    fi
    repo=""$url"github.com/gitaped/dotfiles.git"

    git clone "$repo" "$DOTFILES"
  else
    err "$DOTFILES already exists"
  fi

  cd $DOTFILES
}

case "$(uname -s)" in 
  Darwin)
    which brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    get_dotfiles
    brew update
    brew bundle

    make up
    ;;
  Linux)
    which apt || err "Unsupported Linux"
    sudo apt update
    curl -fsSL https://raw.githubusercontent.com/gitaped/dotfiles/master/packages.list | xargs sudo apt-get --yes install
    get_dotfiles

    make up
    ;;
  *)
    err "Unrecognized OS"
    ;;
esac

exit 0
