#!/bin/bash

echo "[1]: Symlinking the rcm config file"

DOTFILES=$(git rev-parse --show-toplevel)
SOURCE="$DOTFILES/rcrc"
DESTINATION="$HOME/.rcrc"

if [ ! -L "$DESTINATION" ]; then
  ln -sf "$SOURCE" "$DESTINATION"
else
  echo "Skipping. The rcm config file is already symlinked."
fi

exit 0
