#!/bin/bash

DOTFILES=$(git rev-parse --show-toplevel)
SOURCE="$DOTFILES/rcrc"
DESTINATION="$HOME/.rcrc"

if [ ! -f "$DESTINATION" ] && [ -f "$SOURCE" ]; then
    if command ln -sf "$SOURCE" "$DESTINATION"; then
        echo "Successfully installed the initial rcm configuration file"
    else
        echo "Failed installing initial rcm configuration file"
        exit 1
    fi
fi

exit 0
