#!/bin/bash

DOTFILES=~/dotfiles

if [ ! -e $DOTFILES/vim/autoload/plug.vim ]; then
    echo "Downloading vim-plug config file"
    curl --silent -fLo $DOTFILES/vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

if [ ! -e $DOTFILES/vim/colors/badwolf.vim ]; then
    echo "Downloading badwolf vim colorscheme"
    curl --silent -fLo $DOTFILES/vim/colors/badwolf.vim --create-dirs https://bitbucket.org/sjl/badwolf/raw/tip/colors/badwolf.vim
fi

exit 0
