#!/bin/bash

echo "[2]: Setting up vim"

DOTFILES=$(git rev-parse --show-toplevel)
PLUGIN_MANAGER="$DOTFILES/vim/autoload/plug.vim"
COLORSCHEME="$DOTFILES/vim/colors/badwolf.vim"

if [ ! -e $PLUGIN_MANAGER ]; then
  echo "Installing vim plugin manager"
  curl --silent -fLo $PLUGIN_MANAGER --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
else
  echo "Skipping. vim plugin manager already exists."
fi

if [ ! -e $COLORSCHEME ]; then
  echo "Installing vim colorscheme"
  curl --silent -fLo $COLORSCHEME --create-dirs https://raw.githubusercontent.com/sjl/badwolf/master/colors/badwolf.vim
else
  echo "Skipping. vim colorscheme already exists."
fi

exit 0
