#!/bin/bash

WORK_FISH=$(git rev-parse --show-toplevel)/config/fish/work.fish

if [ ! -e $WORK_FISH ]; then
    echo "[3]: Creating work.fish"
    touch $WORK_FISH
else
    echo "[3]: Already existing work.fish"
fi

exit 0
