#!/bin/bash

WORK_GITCONFIG=$(git rev-parse --show-toplevel)/gitconfig-work

if [ ! -e $WORK_GITCONFIG ]; then
  echo "[4]: Creating gitconfig-work"
  touch $WORK_GITCONFIG
  echo "# vim: set ft=gitconfig:" >> $WORK_GITCONFIG
else
  echo "[4]: Already existing gitconfig-work"
fi

exit 0
