.TH GIT-RENAME 1
.SH NAME
git-rename \- Rename the current git branch
.SH SYNOPSIS
.I git rename
[<options>...] <name>
.SH DESCRIPTION
Renames the current local branch and if there exists an accompanying remote,
delete the old remote branch and push the new branch.

.SH OPTIONS
.TP
\-d, \-\-dry\-run
Print debugging information and display the commands that would be executed.
.TP
\-f, \-\-force
Rename the branch immediately without confirmation.

.SH AUTHOR
Ansley Peduru (ansleypeduru96@gmail.com)
