# ZSHRC
local ZSH_CONF=$HOME/dotfiles/zsh

export PS1='%F{11}%n@%m %F{245}%~ %F{11}$ %F{250}'

source $ZSH_CONF/zsh_aliases
source $ZSH_CONF/zsh_functions

export EDITOR=vim
export USE_EDITOR=$EDITOR
export VISUAL=$EDITOR
export KEYTIMEOUT=1

bindkey '^w' backward-kill-word
bindkey "^f" kill-whole-line
bindkey -v

#if [ "$TMUX" = "" ]; then tmux; fi
