#!/bin/bash

echo "[2]: Generating SSH keys"

KEY="$HOME/.ssh/keys/github.com"

mkdir -p $(dirname $KEY)

if [ ! -e $KEY ]; then
  yes | ssh-keygen -o -a 100 -t ed25519 -f $KEY -C "ansleypeduru96@gmail.com" -N ""
else
  echo "Skipping. Already exists."
fi

exit 0
