#!/bin/bash

echo "[2]: Generating SSH keys"

KEY="$HOME/.ssh/keys/github.com"

if [ ! -e $KEY ]; then
  mkdir -p $(dirname $KEY)
  yes 2>/dev/null | ssh-keygen -a 100 -t ed25519 -f $KEY -C "ansleypeduru96@gmail.com" -N ""
else
  echo "Skipping. Already exists."
fi

exit 0
