#!/bin/bash

echo "[2]: Setting fish as the default shell"

if ! grep -Fxq "$(which fish)" /etc/shells; then
  echo "$(which fish)" | sudo tee -a /etc/shells
fi

if [ "$SHELL" != "$(which fish)" ]; then
  sudo chsh -s $(which fish) $(whoami)
fi

exit 0
