#!/bin/bash

echo "[3]: Setting fish as the default shell"

if ! grep -Fxq "$(which fish)" /etc/shells; then
  echo "$(which fish)" | sudo tee -a /etc/shells
fi

if [ "$SHELL" != "$(which fish)" ]; then
  chsh -s $(which fish)
fi

exit 0
